spring:
  application:
    name: rabbitmq-server
  profiles:
    active: dev
  http:
    encoding:
      charset: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL
    time-zone: GMT+8
  rabbitmq:
    # 单机地址
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
#    # 集群地址，用逗号分隔
##    addresses: 127.0.0.1:15672,127.0.0.1:15673
#    addresses: 127.0.0.1:15672
#    connection-timeout: 15000
#    password: guest
#    # 使用启用消息确认模式
#    publisher-confirms: true
#    username: guest
#    virtual-host: /

server:
  # 服务端以89开始，依次88、87
  port: 8789

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown

