spring:
  application:
    name: seeyon-client
  profiles:
    active: dev

server:
  # 客户端以11开始，依次12、13
  port: 8712

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}


