spring:
  datasource:
    druid:
      db1:
        driverClassName: com.mysql.jdbc.Driver
        username: root
        password: root
        # spring2.0此处为jdbc-url
        url: jdbc:mysql://1.14.155.181:3306/zyjkfw?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        type: com.alibaba.druid.pool.DruidDataSource
      db2:
        driverClassName: com.mysql.jdbc.Driver
        username: root
        password: root
        # spring2.0此处为jdbc-url
        url: jdbc:mysql://1.14.155.181:3306/sjgl?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        type: com.alibaba.druid.pool.DruidDataSource