spring:
  datasource:
    url: jdbc:mysql://1.14.155.181:3306/zyjkfw?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root