spring:
  application:
    name: common-dataSources
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 设置访问druid监控页的账号和密码,默认没有
      stat-view-servlet:
        login-username: admin
        login-password: admin

    # 配置扩展插件,配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    use-global-data-source-stat: true

    # 连接池配置
    #连接池建立时创建的初始化连接数
    initial-size: 5
    #连接池中最大的活跃连接数
    max-active: 20
    #连接池中最小的活跃连接数
    min-idle: 5
    #获取连接时最大等待时间，单位毫秒
    max-wait: 60000
    # 打开PSCache，并且指定每个连接上PSCache的大小
    pool-prepared-statements: true
    max-open-prepared-statements: 20

    #在空闲连接回收器线程运行期间休眠的时间值,以毫秒为单位，一般比minEvictableIdleTimeMillis小
    time-between-eviction-runs-millis: 60000
    #连接池中连接，在时间段内一直空闲，被逐出连接池的时间(1000*60*60)，以毫秒为单位
    min-evictable-idle-time-millis: 300000

    # 连接有效性检测
    #是否在连接空闲一段时间后检测其可用性
    test-while-idle: true
    #是否在获得连接后检测其可用性
    test-on-borrow: false
    #是否在连接放回连接池后检测其可用性
    test-on-return: false
    #mysql中为 select 'x'
    #oracle中为 select 1 from dual
    validation-query: SELECT 'x'
  cache:
    ehcache:
      config: classpath:/ehcache.xml

#mybatis-plus:
#  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
#  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
#  mapper-locations: classpath:/mapper/**/*.xml
#  # 别名包扫描，多个package用逗号或者分号分隔
#  type-aliases-package: net.htjs.server.dataSources.ywzx.entity
#
#  configuration:
#    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
#    map-underscore-to-camel-case: true
#    cache-enabled: true
#    #配置JdbcTypeForNull, oracle数据库必须配置
#    jdbc-type-for-null: 'null'
#    #mybatis-plus配置控制台打印完整带参数SQL语句
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#
#  global-config:
#    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#    id-type: 0
#    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#    field-strategy: 2
#    #驼峰下划线转换
#    db-column-underline: true
#    #mp2.3+ 全局表前缀 t_
#    table-prefix: t_
#    #刷新mapper 调试神器
#    refresh-mapper: true
#    #数据库大写下划线转换
#    capital-mode: true
#    #逻辑删除配置（下面3个配置）
#    logic-delete-value: 4
#    logic-not-delete-value: 0




server:
  # 服务端以1开始，依次2、3
  port: 10001

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown

