spring:
  application:
    name: elasticsearch-client
  profiles:
    active: dev
  data:
    elasticsearch:
      client:
        reactive:
          username: guest
          password: guest
          endpoints: localhost:9200
      repositories:
        enabled: false

#      cluster-nodes: localhost:9200
#      cluster-name: es-wyf

server:
  # 客户端以71开始，依次72、73
  port: 8771

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}
