spring:
  application:
    name: zipkin-demo-server
  profiles:
    active: dev
  # zipkin相关配置
  sleuth:
    web:
      client:
        enabled: true
      sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
    base-url: http://localhost:9411/ # 指定了 Zipkin 服务器的地址
    rabbitmq:
    queue: zipkin
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
    virtual-host: infrastructure
    publisher-confirms: true
    #connection-timeout: 1000ms
    template:
    retry:
      enabled: true
    listener:
    simple:
      acknowledge-mode: auto

# zipkin相关配置
zipkin:
  storage:
    type: elasticsearch
    StorageComponent: elasticsearch
    elasticsearch:
      cluster: elasticsearch
      max-requests: 30
      index: zipkin
      index-shards: 3
      index-replicas: 1
      hosts: localhost:9200

server:
  # 客户端以51开始，依次52、53
  port: 8751

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}
