spring:
  application:
    name: zyjk-server
  profiles:
    active: dev

server:
  # 服务端以21开始，依次22、23
  port: 8721

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}